### ISSUE TITLE
spotify widget 

### ISSUE THREAD

**Issue by command-z-z** [0bCdian/Hyprland_dotfiles#4]
thanks for your awesome dotfile! it's cool.
i have a problem how to achieve the spotify widget with some image and button in the right top position.

**Comment by 0bCdian** [comment]
I'm glad you liked my rice! What problems are you having getting the widget running?

**Comment by command-z-z** [comment]
i dont know how to config that spofity widget, is it a waybar module or anysome else?

**Comment by 0bCdian** [comment]
The widget is made with eww, you first have to install eww, and some dependencies for that specific widget, like python, rustup, playerctl, and playerctld, etc, I recommend you read the imports in the metadata.py file I have in the eww directory to see which python libraries are also needed for this widget to work, then when you have everything installed, just execute in the console:

`eww daemon` `eww open --toggle dashboard` which I believe is the name of the window defined in the eww.yuck file.

here's eww's documentation: https://elkowar.github.io/eww/

and here's a pretty good blogpost on how to write your own eww widgets: https://dharmx.is-a.dev/eww-powermenu/

Of course, the eww directory must be placed inside your /home/username/.config directory for all of this to work, since that's where eww  looks for its config files, unless otherwise stated, you can read more about it in the official docs.

**Comment by command-z-z** [comment]
> The widget is made with eww, you first have to install eww, and some dependencies for that specific widget, like python, rustup, playerctl, and playerctld, etc, I recommend you read the imports in the metadata.py file I have in the eww directory to see which python libraries are also needed for this widget to work, then when you have everything installed, just execute in the console:
> 
> `eww daemon` `eww open --toggle dashboard` which I believe is the name of the window defined in the eww.yuck file.
> 
> here's eww's documentation: https://elkowar.github.io/eww/
> 
> and here's a pretty good blogpost on how to write your own eww widgets: https://dharmx.is-a.dev/eww-powermenu/
> 
> Of course, the eww directory must be placed inside your /home/username/.config directory for all of this to work, since that's where eww looks for its config files, unless otherwise stated, you can read more about it in the official docs.

thanks for your reply.
I thought you were using a waybar as your bar. I will have a try for eww:)

**Comment by 0bCdian** [comment]
I am using waybar for the bar, it's just that I use eww for just the widget, I'm currently using other widgets and dropped off the spotify one entirely in my current config in favor of swaync for the notifications/music player widget.

![image](https://github.com/0bCdian/Hyprland_dotfiles/assets/101421807/9690ee00-7f12-4877-b47c-351fadc77df0)
![image](https://github.com/0bCdian/Hyprland_dotfiles/assets/101421807/833dd9e2-553c-4d47-b292-3dbb8f92d8f9)

I hope I helped clarify any questions!

**Comment by command-z-z** [comment]
> 

i get it, thanks for your detailed answer.
